### ISSUE TITLE
How to remove "sidebar-right-toggle"

### ISSUE THREAD

**Issue by NeilAttewell** [mika-el/angular-admin-lte#12]
_Apologies, I accidentally closed the original ticket._

Hi
I don't need the right sidebar, I removed the mk-layout-sidebar-right tag from my app.component.html but how do I remove the gears icon?
![screenshot from 2018-04-09 10-30-38-2](https://user-images.githubusercontent.com/35130683/38487866-f00bea3a-3be1-11e8-8a8d-abfbdea188ae.png)

**Comment by mika-el** [comment]
Hi,

check here https://mika-el.github.io/angular-admin-lte/#/layout/header

```
<mk-layout-header [isSidebarRightToggle]="false">
   ...
</mk-layout-header>
```
