### ISSUE TITLE
Header navbar content dissapears if isSidebarLeftToggle is false

### ISSUE THREAD

**Issue by ruckbeard** [mika-el/angular-admin-lte#13]
Currently the html template for header component looks like this

```html
<header #headerElement class="main-header">
  ...
  <nav *ngIf="isSidebarLeftToggle" class="navbar navbar-static-top">
    <a  #sidebarLeftToggleElement href="#" class="sidebar-toggle">
      ...
    </a>
    ...
    <ng-content></ng-content>
  </nav>
</header>
```

I think it would make more sense to put *ngIf="isSidebarLeftToggle" on the #sidebarLeftToggleElement itself like this

```html
<header #headerElement class="main-header">
  ...
  <nav class="navbar navbar-static-top">
    <a *ngIf="isSidebarLeftToggle" #sidebarLeftToggleElement href="#" class="sidebar-toggle">
      ...
    </a>
    ...
    <ng-content></ng-content>
  </nav>
</header>
```

 I would like to display the navbar and content without having to have the left toggle displaying since I wrote my own custom sidebar toggle in the sidebar itself.

**Comment by mika-el** [comment]
Hi,

*ngIf="isSidebarLeftToggle" has been moved to a tag.

update to 0.4.1 ;)
