### ISSUE TITLE
Is there a way to hide the left menu?

### ISSUE THREAD

**Issue by jiseungjun** [mika-el/angular-admin-lte#14]
Hi :+1: 
I want to create a menu that is displayed according to user rights.
Is there a way to hide the left menu?

**Comment by mika-el** [comment]
Hi,

You could use setSidebarLeftMenu() to change or hide the sidebar left menu accordingly to user rights.

Check this page: [https://mika-el.github.io/angular-admin-lte/#/layout/configuration](https://mika-el.github.io/angular-admin-lte/#/layout/configuration)
