### ISSUE TITLE
Support AdminLte 3

### ISSUE THREAD

**Issue by leduclinh7141** [mika-el/angular-admin-lte#16]
I am using your angular-admin-lte for my project. It is the best angular port for admin-lte I can find now.  Now Admin-lte 3 has just been released its alpha version. Do you have any plan for supporting Admin-lte 3.
I am looking forward to see new version. Thank you very much. You saved my day.

**Comment by mika-el** [comment]
Hi,
Thanks for the feedback ☺️
Yes I'm planning to update to adminLte 3 soon after stable release.

**Comment by iyilm4z** [comment]
Hi @mledour, [AdminLTE v3](https://github.com/ColorlibHQ/AdminLTE/releases/tag/v3.0.0) released with boostrap 4. 

If you don't mind, could you please share your AdminLTE v3 repo with us?
