### ISSUE TITLE
Get started - Dependencies

### ISSUE THREAD

**Issue by chranmat** [mika-el/angular-admin-lte#18]
Hi,

First of all - Great work with with the angular-admin-lte. I use admin-lte from before, but are quite new to angular. Beginning to get it now.

I have downloaded and run this repo from git source, and everything works well. In "Get started" you say that I can include this library to an existing angular project. I have tried to do this.

When I try to add "Dependencies" to the "styles" object in "angular.json" and then run "ng-serve" I get message about paths not found for these dependencies.

I figured that the following packages was missing:
- bootstrap-css-only
- font-awesome
- ionicons
- admin-lte-css

Of course, when installing them manually, I can build successfully. 

Question 1)
Could not these packages be added as dependencies to the npm package "angular-admin-lte" ?

Question 2)
It seems that this git repo is not the actual repo for the npm package it self? 
I might like to fork and add pull requests. Is that possible?

Best regards,
Christian

**Comment by mika-el** [comment]
Hi,

admin-lte-css is served as peerDependencies, you should have seen warnings during first npm install.
bootstrap-css-only is served by admin-lte-css as devDependencie so you need to install it manually or include any other bootstrap. You can install your own customized bootstrap.
ionicons and font-awesome are optional.

The npm package come from the build. npm run build:lib create a dist folder, this is the npm package
You're welcome to create pull request ;)
