### ISSUE TITLE
Get started - Dependency ionicons

### ISSUE THREAD

**Issue by chranmat** [mika-el/angular-admin-lte#19]
Path for ionicons is "node_modules/ionicons/dist/css/ionicons.css", not "node_modules/ionicons/css/ionicons.css" as described on the "Get started" page.

There is also a "min" version available that might is preferable?

**Comment by mika-el** [comment]
You probably have installed ionicons version 3 or 4.
Admin lte 2 is served with inonicons 2.
You can use the minified version but angular will take care of minifying the css anyway.
