### ISSUE TITLE
LayoutStore cannot be injected in 1.2.6

### ISSUE THREAD

**Issue by Mihai-B** [mika-el/angular-admin-lte#22]
Using the version 1.2.6 the Layout.Store cannot be injected anymore.

Did something change and I don't know about

Code Sandbox: https://codesandbox.io/s/1qw7kk2x7l

**Comment by Mihai-B** [comment]
It is the same in 1.2.5, and that used to work. Maybe some dependency problem...

**Comment by mika-el** [comment]
should have been fixed with 1.2.7

**Comment by Mihai-B** [comment]
I cannot make it work. There is a workaround for this, but it should be able to inject like in the code sandbox...

**Comment by mika-el** [comment]
do you still have the problem?

Have you tried the latest version?

**Comment by Mihai-B** [comment]
For some reason, if I try and inject the LayoutStore in AppComponent it doesn't work. If I inject it in another service, it works for some reason... I don't know I will close this issue but the behaviour is a bit strange in my opinion.
