### ISSUE TITLE
Get active tab in mk-tabs

### ISSUE THREAD

**Issue by rakeshbmurthy** [mika-el/angular-admin-lte#27]
Cant capture mk-tabs on click event

**Comment by rakeshbmurthy** [comment]
Cant get active mk-tab inside mk-tabs, or (click) on mk-tab is not working

**Comment by Mihai-B** [comment]
Post a code example on how you are trying to do this

**Comment by mika-el** [comment]
Hi,

You should use it like this:

```
<mk-tabs (onClose)="close($event)">
```

```
  close($event) {
    console.log($event.index);
  }
```
