### ISSUE TITLE
Unstable behavior of sidebar menu

### ISSUE THREAD

**Issue by MRDcoder** [mika-el/angular-admin-lte#28]

**Comment by MRDcoder** [comment]
Hi @mika-el  

can you please help me on below?
the issue faced is opening nested children i.e The first level opens the children links, then clicking on a child link (that has more children) closes all the child links instead of further opening the nested child links.

for instance

sidebarLeftMenu: [
{label: 'MAIN NAVIGATION', separator: true},
{label: 'Start', route: '/', iconClasses: 'fa fa-th'},
{label: 'Parent', iconClasses: 'fa fa-files-o', children: [
{label: 'Children', route: 'parent/children'},
{label: 'Parent 2', children: [
{label: 'Children 2', route: 'parent/parent2/children2'}
]}
...
]}
]
clicking "Parent" will show the child links i.e "Parent 2" while clicking "Parent 2" will instead hide "Parent 2" rather than display child links i.e. "Children 2".

Same happens for simple child menu as well.

I am not sure if it's an issue with the library or how I am doing it since there are no errors in web & angular console.

I tried to debug and found out that menu get toggle (hide) in zone.js code and also if we add one simple separator  like "{label: 'MAIN NAVIGATION', separator: true}," then it will work perfectly.

Please guide me

**Comment by MRDcoder** [comment]
@mika-el any update ?

**Comment by MRDcoder** [comment]
Did you get a chance to look into this issue?

**Comment by mika-el** [comment]
Hi,

fixed with @1.3.1 ;)
