### ISSUE TITLE
How do I log in?

### ISSUE THREAD

**Issue by jiseungjun** [mika-el/angular-admin-lte#3]
How do I log in?

Hello
I want to use the login screen but it does not work.
Should LayoutModule be used only in app.modules.ts?
Can not you use it like this?

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: '<router-outlet></router-outlet>',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'app';
}
```

**Comment by mika-el** [comment]
Hi,

Login screen has not been implemented yet.
No you can't add component on top of layout's component.
I'll work on this soon (maybe add the ability for custom route layout).

**Comment by mika-el** [comment]
HI jiseungjun
Now you can implement login screen or anything you want with custom layout.
Check this [https://mika-el.github.io/angular-admin-lte/#/layout/custom](url)
And this [https://github.com/mika-el/angular-admin-lte/tree/master/demo/src/app/%2Blogin](url)

**Comment by jiseungjun** [comment]
Thank you~ mika-el

**Comment by mika-el** [comment]
;-)
