### ISSUE TITLE
[sidebar-right-toggle] button Is there a setting to hide?

### ISSUE THREAD

**Issue by jiseungjun** [mika-el/angular-admin-lte#5]
HI,

I have a question.

[clsss=sidebar-right-toggle] button Is there a setting to hide?

**Comment by mika-el** [comment]
You can use sidebarRightCollapsed() from layoutStore.


<pre>import { LayoutStore } from 'angular-admin-lte/layout/layout.store';

@Component({
   ...
})
export class TheComponent implements OnInit {
  constructor(private layoutStore: LayoutStore) {}

  ngOnInit() {
    this.layoutStore.sidebarRightCollapsed(true);
  }
}</pre>

**Comment by jiseungjun** [comment]
Thank you~

**Comment by mika-el** [comment]
;)
