### ISSUE TITLE
Non collapsible sub menu 

### ISSUE THREAD

**Issue by NeilAttewell** [mika-el/angular-admin-lte#6]
Hi
In the Sidebar left menu, is it possible to have a label with children without the accordion/collapse?
If so, how?

**Comment by mika-el** [comment]
Hi,
There is no way at this time to disable sub menu collapse feature.
I'll add this feature when I'll have time.

**Comment by jiseungjun** [comment]
Hi,
In the code below, how do I add active?

![1](https://user-images.githubusercontent.com/13620639/38241237-a91cbaec-376c-11e8-8f84-ec81ee726452.png)

**Comment by mika-el** [comment]
Hi,

Can can do this now with @0.4.0. 
Add disableCollapse in adminLteConf:

<pre>
...
{label: 'Layout', iconClasses: 'fa fa-th-list', disableCollapse: true, children: [
   ...
]
</pre>
