### ISSUE TITLE
NullInjectorError: No provider for LayoutStore!

### ISSUE THREAD

**Issue by Luiz-Otavio-Dorigon** [mika-el/angular-admin-lte#7]
Estou tentando utilizar seu template porem estou me deparando com este erro.

<img width="926" alt="captura de tela 2018-03-21 as 13 05 03" src="https://user-images.githubusercontent.com/4552539/37721522-84e4938e-2d08-11e8-814b-e1b0a36fafe5.png">

**Comment by mika-el** [comment]
Hi,
Have you followed this guidelines ? 
https://mika-el.github.io/angular-admin-lte/#/layout/configuration

<pre>import { adminLteConf } from './admin-lte.conf';   //Import the layout configuration.
import { LayoutModule } from 'angular-admin-lte';   //Import the layout module.

@NgModule({
  imports: [
    ...
    LayoutModule.forRoot(adminLteConf),   //Provide the configuration to the layout module.
  ],
  ...
})
export class AppModule {}</pre>

If yes can you reproduce this on a pluncklr
