### ISSUE TITLE
isSidebarLeftxxx in confing does not seems to work

### ISSUE THREAD

**Issue by inkonito** [mika-el/angular-admin-lte#8]
Hi,

First of all, nice work overall :).

I just got one issue when trying to set isSidebarLeftxxx in the configuration:

```
export var adminLteConf = {
...
isSidebarLeftCollapsed: true,
isSidebarLeftMini: true,
sidebarLeftMenu: [
...
]
};
```

I try to set the left sidebar collapsed by default, but it seems the event is not raised in the layout store (maybe the config is loaded before the subscribe handlers are binded ?) so the class "sidebar-collapse" is not set. If i programmatically do it with the layout store, it does not work on OnInit() method, but it works otherwise (or if a put a setTimeout() in my OnInit() )
Any advice on why it does not work with the configuration file?

Thanks

**Comment by mika-el** [comment]
Hi inkonito,

This is a bug.
It have been resolved. Update angular-admin-lte to 0.3.8.

thanks :)

**Comment by inkonito** [comment]
Perfect, it works now.
Thanks for the fast update :)
