### ISSUE TITLE
Is there a way to have the parent menu in the sidebar-left component activated when accessing its child url that is not a fixed value?

### ISSUE THREAD

**Issue by jiseungjun** [mika-el/angular-admin-lte#9]
Hi mika-el

Is there a way to have the parent menu in the sidebar-left component activated
when accessing its child url that is not a fixed value?

![active](https://user-images.githubusercontent.com/13620639/38401298-d927e2be-398f-11e8-9e21-edceb3950329.png)

**Comment by mika-el** [comment]
Hi jiseungjun

Update to angular-admin-lte 0.4.0 then:

<pre>
import { Component, OnInit } from '@angular/core';
import { LayoutStore } from 'angular-admin-lte';

@Component({
  selector: 'app-root',
  templateUrl: './any.component.html'
})
export class AnyComponent implements OnInit {
  constructor(
    private layoutStore: LayoutStore
  ) {}

  ngOnInit() {
    this.layoutStore.setSidebarLeftMenuActiveUrl('classification');
  }
}
</pre>

**Comment by innovm** [comment]
Thank you ;D

**Comment by innovm** [comment]
Hi~

Although this works for a short while after refreshing,
if I try to access it again after going to another menu, the same problem occurs.

**Comment by jiseungjun** [comment]
Hi~

Although this works for a short while after refreshing,
if I try to access it again after going to another menu, the same problem occurs.

**Comment by mika-el** [comment]
You need to do it on each components you want to assign to this menu. Or you can use navigationEnd.

**Comment by jiseungjun** [comment]
thank you!
